var mapping = [
    {'iso2':'AF', 'iso3':'AFG', 'fr':'Afghanistan', 'en':'Afghanistan' },
    {'iso2':'AL', 'iso3':'ALB', 'fr':'Albanie', 'en':'Albania' },
    {'iso2':'AQ', 'iso3':'ATA', 'fr':'Antarctique', 'en':'Antarctica' },
    {'iso2':'DZ', 'iso3':'DZA', 'fr':'Algérie', 'en':'Algeria' },
    {'iso2':'AS', 'iso3':'ASM', 'fr':'Samoa Américaines', 'en':'American Samoa' },
    {'iso2':'AD', 'iso3':'AND', 'fr':'Andorre', 'en':'Andorra' },
    {'iso2':'AO', 'iso3':'AGO', 'fr':'Angola', 'en':'Angola' },
    {'iso2':'AG', 'iso3':'ATG', 'fr':'Antigua-et-Barbuda', 'en':'Antigua and Barbuda' },
    {'iso2':'AZ', 'iso3':'AZE', 'fr':'Azerbaïdjan', 'en':'Azerbaijan' },
    {'iso2':'AR', 'iso3':'ARG', 'fr':'Argentine', 'en':'Argentina' },
    {'iso2':'AU', 'iso3':'AUS', 'fr':'Australie', 'en':'Australia' },
    {'iso2':'AT', 'iso3':'AUT', 'fr':'Autriche', 'en':'Austria' },
    {'iso2':'BS', 'iso3':'BHS', 'fr':'Bahamas', 'en':'Bahamas' },
    {'iso2':'BH', 'iso3':'BHR', 'fr':'Bahreïn', 'en':'Bahrain' },
    {'iso2':'BD', 'iso3':'BGD', 'fr':'Bangladesh', 'en':'Bangladesh' },
    {'iso2':'AM', 'iso3':'ARM', 'fr':'Arménie', 'en':'Armenia' },
    {'iso2':'BB', 'iso3':'BRB', 'fr':'Barbade', 'en':'Barbados' },
    {'iso2':'BE', 'iso3':'BEL', 'fr':'Belgique', 'en':'Belgium' },
    {'iso2':'BM', 'iso3':'BMU', 'fr':'Bermudes', 'en':'Bermuda' },
    {'iso2':'BT', 'iso3':'BTN', 'fr':'Bhoutan', 'en':'Bhutan' },
    {'iso2':'BO', 'iso3':'BOL', 'fr':'Bolivie', 'en':'Bolivia' },
    {'iso2':'BA', 'iso3':'BIH', 'fr':'Bosnie-Herzégovine', 'en':'Bosnia and Herzegovina' },
    {'iso2':'BW', 'iso3':'BWA', 'fr':'Botswana', 'en':'Botswana' },
    {'iso2':'BV', 'iso3':'BVT', 'fr':'Île Bouvet', 'en':'Bouvet Island' },
    {'iso2':'BR', 'iso3':'BRA', 'fr':'Brésil', 'en':'Brazil' },
    {'iso2':'BZ', 'iso3':'BLZ', 'fr':'Belize', 'en':'Belize' },
    {'iso2':'IO', 'iso3':'IOT', 'fr':"Territoire Britannique de l'Océan Indien", 'en':'British Indian Ocean Territory' },
    {'iso2':'SB', 'iso3':'SLB', 'fr':'Îles Salomon', 'en':'Solomon Islands' },
    {'iso2':'VG', 'iso3':'VGB', 'fr':'Îles Vierges Britanniques', 'en':'British Virgin Islands' },
    {'iso2':'BN', 'iso3':'BRN', 'fr':'Brunéi Darussalam', 'en':'Brunei Darussalam' },
    {'iso2':'BG', 'iso3':'BGR', 'fr':'Bulgarie', 'en':'Bulgaria' },
    {'iso2':'MM', 'iso3':'MMR', 'fr':'Myanmar', 'en':'Myanmar' },
    {'iso2':'BI', 'iso3':'BDI', 'fr':'Burundi', 'en':'Burundi' },
    {'iso2':'BY', 'iso3':'BLR', 'fr':'Bélarus', 'en':'Belarus' },
    {'iso2':'KH', 'iso3':'KHM', 'fr':'Cambodge', 'en':'Cambodia' },
    {'iso2':'CM', 'iso3':'CMR', 'fr':'Cameroun', 'en':'Cameroon' },
    {'iso2':'CA', 'iso3':'CAN', 'fr':'Canada', 'en':'Canada' },
    {'iso2':'CV', 'iso3':'CPV', 'fr':'Cap-vert', 'en':'Cape Verde' },
    {'iso2':'KY', 'iso3':'CYM', 'fr':'Îles Caïmanes', 'en':'Cayman Islands' },
    {'iso2':'CF', 'iso3':'CAF', 'fr':'République Centrafricaine', 'en':'Central African' },
    {'iso2':'LK', 'iso3':'LKA', 'fr':'Sri Lanka', 'en':'Sri Lanka' },
    {'iso2':'TD', 'iso3':'TCD', 'fr':'Tchad', 'en':'Chad' },
    {'iso2':'CL', 'iso3':'CHL', 'fr':'Chili', 'en':'Chile' },
    {'iso2':'CN', 'iso3':'CHN', 'fr':'Chine', 'en':'China' },
    {'iso2':'TW', 'iso3':'TWN', 'fr':'Taïwan', 'en':'Taiwan' },
    {'iso2':'CX', 'iso3':'CXR', 'fr':'Île Christmas', 'en':'Christmas Island' },
    {'iso2':'CC', 'iso3':'CCK', 'fr':'Îles Cocos (Keeling)', 'en':'Cocos (Keeling) Islands' },
    {'iso2':'CO', 'iso3':'COL', 'fr':'Colombie', 'en':'Colombia' },
    {'iso2':'KM', 'iso3':'COM', 'fr':'Comores', 'en':'Comoros' },
    {'iso2':'YT', 'iso3':'MYT', 'fr':'Mayotte', 'en':'Mayotte' },
    {'iso2':'CG', 'iso3':'COG', 'fr':'République du Congo', 'en':'Republic of the Congo' },
    {'iso2':'CD', 'iso3':'COD', 'fr':'République Démocratique du Congo', 'en':'The Democratic Republic Of The Congo' },
    {'iso2':'CK', 'iso3':'COK', 'fr':'Îles Cook', 'en':'Cook Islands' },
    {'iso2':'CR', 'iso3':'CRI', 'fr':'Costa Rica', 'en':'Costa Rica' },
    {'iso2':'HR', 'iso3':'HRV', 'fr':'Croatie', 'en':'Croatia' },
    {'iso2':'CU', 'iso3':'CUB', 'fr':'Cuba', 'en':'Cuba' },
    {'iso2':'CY', 'iso3':'CYP', 'fr':'Chypre', 'en':'Cyprus' },
    {'iso2':'CZ', 'iso3':'CZE', 'fr':'République Tchèque', 'en':'Czech Republic' },
    {'iso2':'BJ', 'iso3':'BEN', 'fr':'Bénin', 'en':'Benin' },
    {'iso2':'DK', 'iso3':'DNK', 'fr':'Danemark', 'en':'Denmark' },
    {'iso2':'DM', 'iso3':'DMA', 'fr':'Dominique', 'en':'Dominica' },
    {'iso2':'DO', 'iso3':'DOM', 'fr':'République Dominicaine', 'en':'Dominican Republic' },
    {'iso2':'EC', 'iso3':'ECU', 'fr':'Équateur', 'en':'Ecuador' },
    {'iso2':'SV', 'iso3':'SLV', 'fr':'El Salvador', 'en':'El Salvador' },
    {'iso2':'GQ', 'iso3':'GNQ', 'fr':'Guinée Équatoriale', 'en':'Equatorial Guinea' },
    {'iso2':'ET', 'iso3':'ETH', 'fr':'Éthiopie', 'en':'Ethiopia' },
    {'iso2':'ER', 'iso3':'ERI', 'fr':'Érythrée', 'en':'Eritrea' },
    {'iso2':'EE', 'iso3':'EST', 'fr':'Estonie', 'en':'Estonia' },
    {'iso2':'FO', 'iso3':'FRO', 'fr':'Îles Féroé', 'en':'Faroe Islands' },
    {'iso2':'FK', 'iso3':'FLK', 'fr':'Îles (malvinas) Falkland', 'en':'Falkland Islands' },
    {'iso2':'GS', 'iso3':'SGS', 'fr':'Géorgie du Sud et les Îles Sandwich du Sud', 'en':'South Georgia and the South Sandwich Islands' },
    {'iso2':'FJ', 'iso3':'FJI', 'fr':'Fidji', 'en':'Fiji' },
    {'iso2':'FI', 'iso3':'FIN', 'fr':'Finlande', 'en':'Finland' },
    {'iso2':'AX', 'iso3':'ALA', 'fr':'Îles Åland', 'en':'Åland Islands' },
    {'iso2':'FR', 'iso3':'FRA', 'fr':'France', 'en':'France' },
    {'iso2':'GF', 'iso3':'GUF', 'fr':'Guyane Française', 'en':'French Guiana' },
    {'iso2':'PF', 'iso3':'PYF', 'fr':'Polynésie Française', 'en':'French Polynesia' },
    {'iso2':'TF', 'iso3':'ATF', 'fr':'Terres Australes Françaises', 'en':'French Southern Territories' },
    {'iso2':'DJ', 'iso3':'DJI', 'fr':'Djibouti', 'en':'Djibouti' },
    {'iso2':'GA', 'iso3':'GAB', 'fr':'Gabon', 'en':'Gabon' },
    {'iso2':'GE', 'iso3':'GEO', 'fr':'Géorgie', 'en':'Georgia' },
    {'iso2':'GM', 'iso3':'GMB', 'fr':'Gambie', 'en':'Gambia' },
    {'iso2':'PS', 'iso3':'PSE', 'fr':'Territoire Palestinien Occupé', 'en':'Occupied Palestinian Territory' },
    {'iso2':'DE', 'iso3':'DEU', 'fr':'Allemagne', 'en':'Germany' },
    {'iso2':'GH', 'iso3':'GHA', 'fr':'Ghana', 'en':'Ghana' },
    {'iso2':'GI', 'iso3':'GIB', 'fr':'Gibraltar', 'en':'Gibraltar' },
    {'iso2':'KI', 'iso3':'KIR', 'fr':'Kiribati', 'en':'Kiribati' },
    {'iso2':'GR', 'iso3':'GRC', 'fr':'Grèce', 'en':'Greece' },
    {'iso2':'GL', 'iso3':'GRL', 'fr':'Groenland', 'en':'Greenland' },
    {'iso2':'GD', 'iso3':'GRD', 'fr':'Grenade', 'en':'Grenada' },
    {'iso2':'GP', 'iso3':'GLP', 'fr':'Guadeloupe', 'en':'Guadeloupe' },
    {'iso2':'GU', 'iso3':'GUM', 'fr':'Guam', 'en':'Guam' },
    {'iso2':'GT', 'iso3':'GTM', 'fr':'Guatemala', 'en':'Guatemala' },
    {'iso2':'GN', 'iso3':'GIN', 'fr':'Guinée', 'en':'Guinea' },
    {'iso2':'GY', 'iso3':'GUY', 'fr':'Guyana', 'en':'Guyana' },
    {'iso2':'HT', 'iso3':'HTI', 'fr':'Haïti', 'en':'Haiti' },
    {'iso2':'HM', 'iso3':'HMD', 'fr':'Îles Heard et Mcdonald', 'en':'Heard Island and McDonald Islands' },
    {'iso2':'VA', 'iso3':'VAT', 'fr':'Saint-Siège (état de la Cité du Vatican)', 'en':'Vatican City State' },
    {'iso2':'HN', 'iso3':'HND', 'fr':'Honduras', 'en':'Honduras' },
    {'iso2':'HK', 'iso3':'HKG', 'fr':'Hong-Kong', 'en':'Hong Kong' },
    {'iso2':'HU', 'iso3':'HUN', 'fr':'Hongrie', 'en':'Hungary' },
    {'iso2':'IS', 'iso3':'ISL', 'fr':'Islande', 'en':'Iceland' },
    {'iso2':'IN', 'iso3':'IND', 'fr':'Inde', 'en':'India' },
    {'iso2':'ID', 'iso3':'IDN', 'fr':'Indonésie', 'en':'Indonesia' },
    {'iso2':'IR', 'iso3':'IRN', 'fr':"Iran", 'en':'Islamic Republic of Iran' },
    {'iso2':'IQ', 'iso3':'IRQ', 'fr':'Irak', 'en':'Iraq' },
    {'iso2':'IE', 'iso3':'IRL', 'fr':'Irlande', 'en':'Ireland' },
    {'iso2':'IL', 'iso3':'ISR', 'fr':'Israël', 'en':'Israel' },
    {'iso2':'IT', 'iso3':'ITA', 'fr':'Italie', 'en':'Italy' },
    {'iso2':'CI', 'iso3':'CIV', 'fr':"Côte d'Ivoire", 'en':"Côte d'Ivoire" },
    {'iso2':'JM', 'iso3':'JAM', 'fr':'Jamaïque', 'en':'Jamaica' },
    {'iso2':'JP', 'iso3':'JPN', 'fr':'Japon', 'en':'Japan' },
    {'iso2':'KZ', 'iso3':'KAZ', 'fr':'Kazakhstan', 'en':'Kazakhstan' },
    {'iso2':'JO', 'iso3':'JOR', 'fr':'Jordanie', 'en':'Jordan' },
    {'iso2':'KE', 'iso3':'KEN', 'fr':'Kenya', 'en':'Kenya' },
    {'iso2':'KP', 'iso3':'PRK', 'fr':'Corée du Nord', 'en':"Democratic People's Republic of Korea" },
    {'iso2':'KR', 'iso3':'KOR', 'fr':'Corée du Sud', 'en':'Republic of Korea' },
    {'iso2':'KW', 'iso3':'KWT', 'fr':'Koweït', 'en':'Kuwait' },
    {'iso2':'KG', 'iso3':'KGZ', 'fr':'Kirghizistan', 'en':'Kyrgyzstan' },
    {'iso2':'LA', 'iso3':'LAO', 'fr':'République Démocratique Populaire Lao', 'en':"Lao People's Democratic Republic" },
    {'iso2':'LB', 'iso3':'LBN', 'fr':'Liban', 'en':'Lebanon' },
    {'iso2':'LS', 'iso3':'LSO', 'fr':'Lesotho', 'en':'Lesotho' },
    {'iso2':'LV', 'iso3':'LVA', 'fr':'Lettonie', 'en':'Latvia' },
    {'iso2':'LR', 'iso3':'LBR', 'fr':'Libéria', 'en':'Liberia' },
    {'iso2':'LY', 'iso3':'LBY', 'fr':'Jamahiriya Arabe Libyenne', 'en':'Libyan Arab Jamahiriya' },
    {'iso2':'LI', 'iso3':'LIE', 'fr':'Liechtenstein', 'en':'Liechtenstein' },
    {'iso2':'LT', 'iso3':'LTU', 'fr':'Lituanie', 'en':'Lithuania' },
    {'iso2':'LU', 'iso3':'LUX', 'fr':'Luxembourg', 'en':'Luxembourg' },
    {'iso2':'MO', 'iso3':'MAC', 'fr':'Macao', 'en':'Macao' },
    {'iso2':'MG', 'iso3':'MDG', 'fr':'Madagascar', 'en':'Madagascar' },
    {'iso2':'MW', 'iso3':'MWI', 'fr':'Malawi', 'en':'Malawi' },
    {'iso2':'MY', 'iso3':'MYS', 'fr':'Malaisie', 'en':'Malaysia' },
    {'iso2':'MV', 'iso3':'MDV', 'fr':'Maldives', 'en':'Maldives' },
    {'iso2':'ML', 'iso3':'MLI', 'fr':'Mali', 'en':'Mali' },
    {'iso2':'MT', 'iso3':'MLT', 'fr':'Malte', 'en':'Malta' },
    {'iso2':'MQ', 'iso3':'MTQ', 'fr':'Martinique', 'en':'Martinique' },
    {'iso2':'MR', 'iso3':'MRT', 'fr':'Mauritanie', 'en':'Mauritania' },
    {'iso2':'MU', 'iso3':'MUS', 'fr':'Maurice', 'en':'Mauritius' },
    {'iso2':'MX', 'iso3':'MEX', 'fr':'Mexique', 'en':'Mexico' },
    {'iso2':'MC', 'iso3':'MCO', 'fr':'Monaco', 'en':'Monaco' },
    {'iso2':'MN', 'iso3':'MNG', 'fr':'Mongolie', 'en':'Mongolia' },
    {'iso2':'MD', 'iso3':'MDA', 'fr':'Moldavie', 'en':'Republic of Moldova' },
    {'iso2':'MS', 'iso3':'MSR', 'fr':'Montserrat', 'en':'Montserrat' },
    {'iso2':'MA', 'iso3':'MAR', 'fr':'Maroc', 'en':'Morocco' },
    {'iso2':'MZ', 'iso3':'MOZ', 'fr':'Mozambique', 'en':'Mozambique' },
    {'iso2':'OM', 'iso3':'OMN', 'fr':'Oman', 'en':'Oman' },
    {'iso2':'NA', 'iso3':'NAM', 'fr':'Namibie', 'en':'Namibia' },
    {'iso2':'NR', 'iso3':'NRU', 'fr':'Nauru', 'en':'Nauru' },
    {'iso2':'NP', 'iso3':'NPL', 'fr':'Népal', 'en':'Nepal' },
    {'iso2':'NL', 'iso3':'NLD', 'fr':'Pays-Bas', 'en':'Netherlands' },
    {'iso2':'AN', 'iso3':'ANT', 'fr':'Antilles Néerlandaises', 'en':'Netherlands Antilles' },
    {'iso2':'AW', 'iso3':'ABW', 'fr':'Aruba', 'en':'Aruba' },
    {'iso2':'NC', 'iso3':'NCL', 'fr':'Nouvelle-Calédonie', 'en':'New Caledonia' },
    {'iso2':'VU', 'iso3':'VUT', 'fr':'Vanuatu', 'en':'Vanuatu' },
    {'iso2':'NZ', 'iso3':'NZL', 'fr':'Nouvelle-Zélande', 'en':'New Zealand' },
    {'iso2':'NI', 'iso3':'NIC', 'fr':'Nicaragua', 'en':'Nicaragua' },
    {'iso2':'NE', 'iso3':'NER', 'fr':'Niger', 'en':'Niger' },
    {'iso2':'NG', 'iso3':'NGA', 'fr':'Nigéria', 'en':'Nigeria' },
    {'iso2':'NU', 'iso3':'NIU', 'fr':'Niué', 'en':'Niue' },
    {'iso2':'NF', 'iso3':'NFK', 'fr':'Île Norfolk', 'en':'Norfolk Island' },
    {'iso2':'NO', 'iso3':'NOR', 'fr':'Norvège', 'en':'Norway' },
    {'iso2':'MP', 'iso3':'MNP', 'fr':'Îles Mariannes du Nord', 'en':'Northern Mariana Islands' },
    {'iso2':'UM', 'iso3':'UMI', 'fr':'Îles Mineures Éloignées des États-Unis', 'en':'United States Minor Outlying Islands' },
    {'iso2':'FM', 'iso3':'FSM', 'fr':'États Fédérés de Micronésie', 'en':'Federated States of Micronesia' },
    {'iso2':'MH', 'iso3':'MHL', 'fr':'Îles Marshall', 'en':'Marshall Islands' },
    {'iso2':'PW', 'iso3':'PLW', 'fr':'Palaos', 'en':'Palau' },
    {'iso2':'PK', 'iso3':'PAK', 'fr':'Pakistan', 'en':'Pakistan' },
    {'iso2':'PA', 'iso3':'PAN', 'fr':'Panama', 'en':'Panama' },
    {'iso2':'PG', 'iso3':'PNG', 'fr':'Papouasie-Nouvelle-Guinée', 'en':'Papua New Guinea' },
    {'iso2':'PY', 'iso3':'PRY', 'fr':'Paraguay', 'en':'Paraguay' },
    {'iso2':'PE', 'iso3':'PER', 'fr':'Pérou', 'en':'Peru' },
    {'iso2':'PH', 'iso3':'PHL', 'fr':'Philippines', 'en':'Philippines' },
    {'iso2':'PN', 'iso3':'PCN', 'fr':'Pitcairn', 'en':'Pitcairn' },
    {'iso2':'PL', 'iso3':'POL', 'fr':'Pologne', 'en':'Poland' },
    {'iso2':'PT', 'iso3':'PRT', 'fr':'Portugal', 'en':'Portugal' },
    {'iso2':'GW', 'iso3':'GNB', 'fr':'Guinée-Bissau', 'en':'Guinea-Bissau' },
    {'iso2':'TL', 'iso3':'TLS', 'fr':'Timor-Leste', 'en':'Timor-Leste' },
    {'iso2':'PR', 'iso3':'PRI', 'fr':'Porto Rico', 'en':'Puerto Rico' },
    {'iso2':'QA', 'iso3':'QAT', 'fr':'Qatar', 'en':'Qatar' },
    {'iso2':'RE', 'iso3':'REU', 'fr':'Réunion', 'en':'Réunion' },
    {'iso2':'RO', 'iso3':'ROU', 'fr':'Roumanie', 'en':'Romania' },
    {'iso2':'RU', 'iso3':'RUS', 'fr':'Russie', 'en':'Russian Federation' },
    {'iso2':'RW', 'iso3':'RWA', 'fr':'Rwanda', 'en':'Rwanda' },
    {'iso2':'SH', 'iso3':'SHN', 'fr':'Sainte-Hélène', 'en':'Saint Helena' },
    {'iso2':'KN', 'iso3':'KNA', 'fr':'Saint-Kitts-et-Nevis', 'en':'Saint Kitts and Nevis' },
    {'iso2':'AI', 'iso3':'AIA', 'fr':'Anguilla', 'en':'Anguilla' },
    {'iso2':'LC', 'iso3':'LCA', 'fr':'Sainte-Lucie', 'en':'Saint Lucia' },
    {'iso2':'PM', 'iso3':'SPM', 'fr':'Saint-Pierre-et-Miquelon', 'en':'Saint-Pierre and Miquelon' },
    {'iso2':'VC', 'iso3':'VCT', 'fr':'Saint-Vincent-et-les Grenadines', 'en':'Saint Vincent and the Grenadines' },
    {'iso2':'SM', 'iso3':'SMR', 'fr':'Saint-Marin', 'en':'San Marino' },
    {'iso2':'ST', 'iso3':'STP', 'fr':'Sao Tomé-et-Principe', 'en':'Sao Tome and Principe' },
    {'iso2':'SA', 'iso3':'SAU', 'fr':'Arabie Saoudite', 'en':'Saudi Arabia' },
    {'iso2':'SN', 'iso3':'SEN', 'fr':'Sénégal', 'en':'Senegal' },
    {'iso2':'SC', 'iso3':'SYC', 'fr':'Seychelles', 'en':'Seychelles' },
    {'iso2':'SL', 'iso3':'SLE', 'fr':'Sierra Leone', 'en':'Sierra Leone' },
    {'iso2':'SG', 'iso3':'SGP', 'fr':'Singapour', 'en':'Singapore' },
    {'iso2':'SK', 'iso3':'SVK', 'fr':'Slovaquie', 'en':'Slovakia' },
    {'iso2':'VN', 'iso3':'VNM', 'fr':'Viet Nam', 'en':'Vietnam' },
    {'iso2':'SI', 'iso3':'SVN', 'fr':'Slovénie', 'en':'Slovenia' },
    {'iso2':'SO', 'iso3':'SOM', 'fr':'Somalie', 'en':'Somalia' },
    {'iso2':'ZA', 'iso3':'ZAF', 'fr':'Afrique du Sud', 'en':'South Africa' },
    {'iso2':'ZW', 'iso3':'ZWE', 'fr':'Zimbabwe', 'en':'Zimbabwe' },
    {'iso2':'ES', 'iso3':'ESP', 'fr':'Espagne', 'en':'Spain' },
    {'iso2':'EH', 'iso3':'ESH', 'fr':'Sahara Occidental', 'en':'Western Sahara' },
    {'iso2':'SD', 'iso3':'SDN', 'fr':'Soudan', 'en':'Sudan' },
    {'iso2':'SR', 'iso3':'SUR', 'fr':'Suriname', 'en':'Suriname' },
    {'iso2':'SJ', 'iso3':'SJM', 'fr':'Svalbard etÎle Jan Mayen', 'en':'Svalbard and Jan Mayen' },
    {'iso2':'SZ', 'iso3':'SWZ', 'fr':'Swaziland', 'en':'Swaziland' },
    {'iso2':'SE', 'iso3':'SWE', 'fr':'Suède', 'en':'Sweden' },
    {'iso2':'CH', 'iso3':'CHE', 'fr':'Suisse', 'en':'Switzerland' },
    {'iso2':'SY', 'iso3':'SYR', 'fr':'Syrie', 'en':'Syrian Arab Republic' },
    {'iso2':'TJ', 'iso3':'TJK', 'fr':'Tadjikistan', 'en':'Tajikistan' },
    {'iso2':'TH', 'iso3':'THA', 'fr':'Thaïlande', 'en':'Thailand' },
    {'iso2':'TG', 'iso3':'TGO', 'fr':'Togo', 'en':'Togo' },
    {'iso2':'TK', 'iso3':'TKL', 'fr':'Tokelau', 'en':'Tokelau' },
    {'iso2':'TO', 'iso3':'TON', 'fr':'Tonga', 'en':'Tonga' },
    {'iso2':'TT', 'iso3':'TTO', 'fr':'Trinité-et-Tobago', 'en':'Trinidad and Tobago' },
    {'iso2':'AE', 'iso3':'ARE', 'fr':'Émirats Arabes Unis', 'en':'United Arab Emirates' },
    {'iso2':'TN', 'iso3':'TUN', 'fr':'Tunisie', 'en':'Tunisia' },
    {'iso2':'TR', 'iso3':'TUR', 'fr':'Turquie', 'en':'Turkey' },
    {'iso2':'TM', 'iso3':'TKM', 'fr':'Turkménistan', 'en':'Turkmenistan' },
    {'iso2':'TC', 'iso3':'TCA', 'fr':'Îles Turks et Caïques', 'en':'Turks and Caicos Islands' },
    {'iso2':'TV', 'iso3':'TUV', 'fr':'Tuvalu', 'en':'Tuvalu' },
    {'iso2':'UG', 'iso3':'UGA', 'fr':'Ouganda', 'en':'Uganda' },
    {'iso2':'UA', 'iso3':'UKR', 'fr':'Ukraine', 'en':'Ukraine' },
    {'iso2':'MK', 'iso3':'MKD', 'fr':"Macédoine", 'en':'The Former Yugoslav Republic of Macedonia' },
    {'iso2':'EG', 'iso3':'EGY', 'fr':'Égypte', 'en':'Egypt' },
    {'iso2':'GB', 'iso3':'GBR', 'fr':'Royaume-Uni', 'en':'United Kingdom' },
    {'iso2':'IM', 'iso3':'IMN', 'fr':'Île de Man', 'en':'Isle of Man' },
    {'iso2':'TZ', 'iso3':'TZA', 'fr':'République-Unie de Tanzanie', 'en':'United Republic Of Tanzania' },
    {'iso2':'US', 'iso3':'USA', 'fr':'États-Unis', 'en':'United States' },
    {'iso2':'VI', 'iso3':'VIR', 'fr':'Îles Vierges des États-Unis', 'en':'U.S. Virgin Islands' },
    {'iso2':'BF', 'iso3':'BFA', 'fr':'Burkina Faso', 'en':'Burkina Faso' },
    {'iso2':'UY', 'iso3':'URY', 'fr':'Uruguay', 'en':'Uruguay' },
    {'iso2':'UZ', 'iso3':'UZB', 'fr':'Ouzbékistan', 'en':'Uzbekistan' },
    {'iso2':'VE', 'iso3':'VEN', 'fr':'Venezuela', 'en':'Venezuela' },
    {'iso2':'WF', 'iso3':'WLF', 'fr':'Wallis et Futuna', 'en':'Wallis and Futuna' },
    {'iso2':'WS', 'iso3':'WSM', 'fr':'Samoa', 'en':'Samoa' },
    {'iso2':'YE', 'iso3':'YEM', 'fr':'Yémen', 'en':'Yemen' },
    {'iso2':'CS', 'iso3':'SCG', 'fr':'Serbie-et-Monténégro', 'en':'Serbia and Montenegro' },
    {'iso2':'ZM', 'iso3':'ZMB', 'fr':'Zambie', 'en':'Zambia' },
];

function getBy(property, value){
    console.log("Trying to get city where city." + property + " = " + value);

    var found = mapping.filter(function(country){
         return country.hasOwnProperty(property) && country[property] == value.toString().toUpperCase();
    });

    return found.length == 0 ? null : found[0];
}